from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "seeding_admin"
down_revision: Union[str, Sequence[str], None] = "2228a83cb340"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

users_table = sa.table(
    "users",
    sa.column("id", sa.BigInteger),
    sa.column("username", sa.String),
    sa.column("email", sa.String),
    sa.column("hashed_password", sa.String),
)


def upgrade() -> None:
    """Upgrade schema."""
    initial_data = [
        {
            "id": 1,
            "username": "admin",
            "email": "admin@email.ru",
            "hashed_password": "$2b$12$yd.0JNLmiWgkgReH8W8zDOZecGLLyRGSNHM42Q.O468YRkt2fkAt6",
        }
    ]
    op.bulk_insert(users_table, initial_data)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE username = 'admin'")
    # ### end Alembic commands ###
